#!/bin/sh
# Writes the third-party notices for the crates compiled into the binaries for
# the targets given as arguments. The MIT, BSD, MPL and Unicode licences in the
# dependency tree all require their notices to travel with the binaries, so
# every release archive and package ships the generated file.
#
# Where a crate offers a choice of licences, MIT is elected: it matches
# quietmouse's own licence and keeps the notices short. Every "OR" in the tree
# offers MIT, so nothing needs the Apache or Zlib text.
#
# Usage: sh scripts/third-party-notices.sh <target-triple>... > THIRD-PARTY-NOTICES.md
set -eu

if [ $# -eq 0 ]; then
    echo "usage: $0 <target-triple>..." >&2
    exit 2
fi

cargo_home=${CARGO_HOME:-$HOME/.cargo}
work=$(mktemp -d)
trap 'rm -rf "$work"' EXIT

: > "$work/crates.tsv"
for target in "$@"; do
    cargo metadata --format-version 1 --filter-platform "$target" --locked \
        | jq -r '
            [.resolve.nodes[].id] as $ids
            | .packages[]
            | select(.id as $i | $ids | index($i))
            | select(.name != "quietmouse" and .name != "hidpp")
            | [.name, .version, (.license // "unspecified"),
               (.repository // ""), ((.authors // []) | join(", "))]
            | @tsv' >> "$work/crates.tsv"
done
sort -u "$work/crates.tsv" > "$work/unique.tsv"

# The unpacked source of a crate, which is where its licence files live.
crate_dir() {
    for root in "$cargo_home"/registry/src/*/; do
        if [ -d "$root$1-$2" ]; then
            printf '%s' "$root$1-$2"
            return 0
        fi
    done
    return 1
}

# LICENSE-MIT first, so a crate offering a choice contributes its MIT text.
licence_file() {
    for name in LICENSE-MIT LICENSE.txt LICENSE LICENSE.md LICENCE COPYING UNLICENSE; do
        if [ -f "$1/$name" ]; then
            printf '%s' "$1/$name"
            return 0
        fi
    done
    return 1
}

targets_include_macos=no
for target in "$@"; do
    case "$target" in *-apple-darwin) targets_include_macos=yes ;; esac
done

cat <<'HEADER'
# Third-party notices

quietmouse itself is MIT-licensed; see LICENSE. The binaries it ships are
statically linked, so they contain code from the crates listed here, and these
are their licences.

Where a crate offers a choice of licences, MIT is elected.

This file is generated by `scripts/third-party-notices.sh` from the crates that
are actually compiled for the platform it is shipped with.
HEADER

if [ "$targets_include_macos" = yes ]; then
    hidapi_version=$(awk -F'\t' '$1 == "hidapi" { print $2; exit }' "$work/unique.tsv")
    hidapi_dir=""
    if [ -n "$hidapi_version" ]; then
        hidapi_dir=$(crate_dir hidapi "$hidapi_version") || hidapi_dir=""
    fi
    if [ -n "$hidapi_dir" ]; then
        bsd=$hidapi_dir/etc/hidapi/LICENSE-bsd.txt
        if [ -f "$bsd" ]; then
            cat <<'NOTE'

## HIDAPI (C library, in the macOS binaries)

The macOS binaries statically link the HIDAPI C library, which is offered under
GPL-3.0, a BSD-style licence, or its original licence, at the choice of the
user of HIDAPI. quietmouse uses it under the BSD-style licence, reproduced here.

NOTE
            printf '```\n'
            cat "$bsd"
            printf '```\n'
        fi
    fi
fi

printf '\n## Crates\n'

: > "$work/nofile.tsv"
while IFS="$(printf '\t')" read -r name version licence repository authors; do
    [ -n "$name" ] || continue
    printf '\n### %s %s\n\n' "$name" "$version"
    if [ -n "$repository" ]; then
        printf '%s\n\n' "$repository"
    fi
    printf 'Licence: %s\n' "$licence"

    dir=$(crate_dir "$name" "$version") || dir=""
    file=""
    if [ -n "$dir" ]; then
        file=$(licence_file "$dir") || file=""
    fi

    if [ -n "$file" ]; then
        printf '\n```\n'
        cat "$file"
        printf '```\n'
        # An AND, not a choice: the Unicode terms apply on top of MIT.
        case "$licence" in
            *Unicode-3.0*)
                if [ -f "$dir/LICENSE-UNICODE" ]; then
                    printf '\nand, additionally:\n\n```\n'
                    cat "$dir/LICENSE-UNICODE"
                    printf '```\n'
                fi
                ;;
        esac
        case "$licence" in
            MPL-2.0)
                printf '\nThis crate is unmodified. Its source is available from %s\n' \
                    "${repository:-crates.io}"
                ;;
        esac
    else
        printf '\nThis crate ships no licence file. Copyright is held by its authors'
        if [ -n "$authors" ]; then
            printf ' (%s)' "$authors"
        fi
        printf ', under the terms it declares above; the MIT text is at the end of this file.\n'
        printf '%s\t%s\n' "$name" "$version" >> "$work/nofile.tsv"
    fi
done < "$work/unique.tsv"

if [ -s "$work/nofile.tsv" ]; then
    cat <<'MIT'

## The MIT License

Reproduced for the crates above that declare MIT but ship no licence file.
Copyright is held by each crate's own authors, named with the crate.

```
Permission is hereby granted, free of charge, to any person obtaining a copy of
this software and associated documentation files (the "Software"), to deal in
the Software without restriction, including without limitation the rights to
use, copy, modify, merge, publish, distribute, sublicense, and/or sell copies of
the Software, and to permit persons to whom the Software is furnished to do so,
subject to the following conditions:

The above copyright notice and this permission notice shall be included in all
copies or substantial portions of the Software.

THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY, FITNESS
FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE AUTHORS OR
COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER LIABILITY, WHETHER
IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN
CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE SOFTWARE.
```
MIT
fi
